{
  "dev": {
    "base_url": "https://dev-api.example.com",
    "timeout": 10
  },
  "test": {
    "base_url": "http://api-test.2house.com",
    "timeout": 15
  },
  "pre": {
    "base_url": "https://pre-api.example.com",
    "timeout": 10
  },
  "prod": {
    "base_url": "https://api.example.com",
    "timeout": 8
  }
}
